[package]
name = "sf2exporter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustysynth="1.3.1"
hound = "3.5.1"
clap = { version = "4.4.8", features=["derive"] }